defaults: &defaults
  from: "noreply@are-you.in"
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  username: "paksols@gmail.com"
  password: "123jkl123jkl"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  from: "noreply@are-you.in"
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  username: "paksols@gmail.com"
  password: "123jkl123jkl"