defaults: &defaults
  from: "noreply@are-you.in"
  address: "smtp.mandrillapp.com"
  port: 587
  domain: "mandrillapp.com"
  username: "florian@designingit.com"
  password: "PumE08VKZPm76YlAdqDFKA"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  from: "noreply@are-you.in"
  address: "smtp.mandrillapp.com"
  port: 587
  domain: "mandrillapp.com"
  username: "florian@designingit.com"
  password: "PumE08VKZPm76YlAdqDFKA"