defaults: &defaults
  from: "noreply@are-you.in"
  address: "mail.aldaimsolutions.com"
  port: 25
  domain: "aldaimsolutions.com"
  username: "noreply@aldaimsolutions.com"
  password: "Admin1234"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  from: "noreply@are-you.in"
  address: "mail.aldaimsolutions.com"
  port: 25
  domain: "aldaimsolutions.com"
  username: "noreply@aldaimsolutions.com"
  password: "Admin1234"